create table if not exists users
(
    user_id bigint generated by default as identity primary key,
    email     varchar(320) not null,
    name     varchar(200) not null,
     unique (email)
);
create table if not exists items
(
    item_id bigint generated by default as identity primary key,
    name     varchar(200) not null,
    description     varchar(200) not null,
    available boolean not null,
    owner_id bigint not null,
    constraint fk_items_owner_id
           foreign key (owner_id)
           references users (user_id)

);
